### PR TITLE
"simuraculum" to "simulacrum"

### PR DESCRIPTION
**Pull request by Determancer**
I was wondering if the word "simuraculum" should be "simulacrum", as the former seems to be a non-existent noun.
If I was wrong, please accept my apologies for bothering you.

### CODE REVIEW

**Comment by Shinoow** [comment]
I'm a bit on the fence about this one. On one hand "simulacrum" is the defined term, but I've seen "simuraculum" in places online (and someone also brought that word up in a conversation years ago, which is why it's there).
I might do a poll on this, and get a consensus on the matter.

**Comment by Determancer** [comment]
I found one result that should be relevant: [https://books.google.com/books?id=-MZQAAAAcAAJ&pg=PA39&lpg=PA39&dq=simuraculum&source=bl&ots=ZHlsMEH88g&sig=ACfU3U14qzZwfiqaEGdt4o_ykbNAoxPy9w&hl=en&sa=X&ved=2ahUKEwj73JD-hfXoAhWs0eAKHYpZCS4Q6AEwBHoECAsQJw#v=onepage&q=simuraculum&f=false](url)
It seems like a book written in Latin. May be the word "simuraculum" did exist, and it's just forgotten by the mojority.

**Comment by Determancer** [comment]
A Latin learner told me that according to the prefix and suffix of the word, "simuraculum" seems to be "similarly". But he is not quite sure about that, still trying to figure out the meaning by the comtext.

**Comment by Shinoow** [comment]
I mean, that adds up pretty well. With "simulacrum" being described as `A simulacrum is a representation or imitation of a person or thing`, if "similarly" is regarded in the context of "similarly to", they could be two variations of the same word (where one is more established, and the other is, well, not).
I think I'm gonna go down the route of doing a poll, where the outcome of that will decide which word is used.

**Pull request merged**
